import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import { Toaster } from 'react-hot-toast'
import StoreProvider from './StoreProvider'
import SideBar from '@/components/navigation/SideBar'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Food App V2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
<StoreProvider>
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
     
        {/* Include any additional meta tags, stylesheets, or scripts here */}
      </head>
      <body className={inter.className}>
        <div>
          <Toaster />
        </div>
        {children}
   
     
        <SideBar/>
      </body>
      
    </html>
    </StoreProvider>

  )
}
